### ISSUE TITLE
Get budget data into format for flow diagram

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#23]

**Comment by imonthercks** [comment]
I have started working on this issue.  Working on getting the data/2017-wichita-adopted-budget.csv file converted to the same format as _src/data/flow/FY16-17__adjusted.csv.  Curious if the expectationis to show the level 1, 2 or 3 categories along the borders of the flow diagram?  Will push something soon so you can see what it looks like.

**Comment by imonthercks** [comment]
just wanted to get some feedback on the progress on the flow diagram.  Currently it works, but I think it is probably at the wrong level and some of the data may be misaligned.
![image](https://cloud.githubusercontent.com/assets/1477296/24733961/86681dd8-1a40-11e7-93a7-0f036f340a28.png)
Any thoughts?

**Comment by sethetter** [comment]
@imonthercks yeah something is off. The "General Fund" on the right should be in the middle, and should probably be taking up most of the space.

[Looking at the flow graph js](https://github.com/openwichita/openbudgetwichita/blob/c5a1a29a9b8d19d503d42902ab12f3a70979f269/_src/js/flow.js#L121) it looks like it's using a hardcoded fund code from the CSV. So we'll need something that can take our CSV file and convert it into something that works with what the JS is expecting. We should have all the necessary columns it looks like though!

**Comment by imonthercks** [comment]
Yeah, I had done the conversion only on one side, which is why it showed up like that.  Also missed that it was using different columns in the csv for the Revenue vs Expense side.  making more sense now.  I'll post a picture when I get it closer to the Oakland version to see if there is anything else that stands out to a more trained eye than my own.

**Comment by imonthercks** [comment]
This is looking better, although General Fund still appears to be less than expected.  Right now I am only mapping anything with fund 100 to the General Fund, and anything else is going to Discretionary.  If there is a mapping of funds somewhere that I am not seeing let me know.

The Oakland flow diagram did some explicit sorting of different departments and programs.  I might take a try at it based on what they had, and see how it looks.

![image](https://cloud.githubusercontent.com/assets/1477296/24736030/5d226298-1a4b-11e7-8d2c-60db99bfc74f.png)

**Comment by sethetter** [comment]
@imonthercks it looks like 236 is `General Fund - Economic Development Subf`. That should probably be included there, I would assume.

**Comment by sethetter** [comment]
@imonthercks could you push this to a branch somewhere? I'd like to see the data and also be able to show it to Elizabeth for scrutiny. She's the SME for this project :)

**Comment by imonthercks** [comment]
@sethetter I have checked my changes into my repo at https://github.com/imonthercks/openbudgetwichita.  Ruby script to convert data is in data-utilities and resulting data is in _src/data/flow.  I plan to be back at it this week, so would appreciate any feedback.

**Comment by imonthercks** [comment]
@sethetter I fixed fund 236 to put into General Fund and sorted some of the different categories to make the diagram appear a little cleaner.  I'll be interested to hear any feedback.

**Comment by imonthercks** [comment]
Here is the latest flow diagram on my local fork.  I feel like the Revenue side is missing some detail, and probably some of those categories can be further broken out, just not sure which ones.  I tried to reorder to make the flow diagram a little less busy.

![image](https://cloud.githubusercontent.com/assets/1477296/25464189/94bab37e-2ac0-11e7-96a2-42ee9dcc751c.png)

Any feedback is welcome!

**Comment by sethetter** [comment]
It seems good to me, except for the gaps on the revenue side, I'm still not sure how to explain those.

I'm going to send this to our contact at the city to see if what she thinks. I'll let you know!

**Comment by sethetter** [comment]
@imonthercks here's what Elizabeth had to say:

> First of all, the title “Non-discretionary Funds” is not one that we use. I think that it would be more appropriate to use the term “Other Funds.”
 
I also asked about the gaps between revenue and expenditures:

> Can you explain what you mean by “gaps on the revenue side of things?” Do you mean at the bottom of the chart because there is less revenue than expenditures? I think that the simplest explanation is that funds have more expenditure authority that revenue (unbalanced) because all but 5% of the fund balance needs appropriated in order to comply with the Kansas State Statutes for the budget law…the only exceptions are Transit and Golf, which aren’t certified by the state.

Seems like this would be a good clarification to leave in the page :)

**Comment by sethetter** [comment]
@imonthercks I asked her if she has recommended text for explaining the gap, or if we should adapt what was in her email. I'll report back :)
